name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
